### ISSUE TITLE
Gene Annotation in IGV Session

### ISSUE THREAD

**Issue by ktrns** [nf-core/cutandrun#194]
### Description of the bug

Dear all, 

Thank you for actively developing and improving this pipeline. We have successfully run it for the first time. 

We have observed one issue, which I will try to describe in the following:

I provided gene annotation as `EnsemblGene-104.hg38.TR.gtf`. The IGV session file includes `EnsemblGene-104.hg38.TR.bed.bed.gz`. Unfortunately it is **not** possible to search for gene names. We briefly chatted in Slack about it. 

If I manually load the original `EnsemblGene-104.hg38.TR.gtf` file into the same session, it is still not possible to search for gene names. However, if I load a simplified version of that `gtf` file - in which we manually merged multiple transcripts of the same gene into only one - it is possible to search for gene names. 

I haven't had the time to look deeper into this, but do you think that perhaps IGV gets confused if multiple entries have the same name? This is something I/we can systematically try. I will let you know if I find out more. 

Best wishes for now,
Katrin

**Comment by MRonzio** [comment]
I had a similar issue with ncbi Refseq GTF. In the IGV folder I found `genes.bed.bed.gz`. With this setting, you can't search genes on IGV. But, if you extract the gz file, running
`gunzip -k genes.bed.bed.gz`
You will get an extra file in the folder named `genes.bed.bed`
Now, edit the `igv_session.xml` file, replacing `genes.bed.bed.gz` entries to `genes.bed.bed`.
Re-opening IGV calling the edited `igv_session.xml` you should have restored the search function.
I don't know if it is caused by some library missing on my side or else, but it seems to be related to the gzipped nature of the file. Your clear GTF file should have been fine, though.
